services:
  app:
    build: .
    command: tail -f /dev/null
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
      CACHE_STORE: ${CACHE_STORE}
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - expertiza-mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6380:6380"
    volumes:
      - expertiza-redis:/var/lib/redis/data

volumes:
  expertiza-mysql:
  expertiza-redis:
