x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  app:
    build: .
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
      CACHE_STORE: ${CACHE_STORE}
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - public
      - private
    logging: *default-logging

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - expertiza-mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - private
    logging: *default-logging

  redis:
    image: redis:latest
    volumes:
      - expertiza-redis:/var/lib/redis/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--port", "6380", "--maxmemory", "100mb"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - private
    logging: *default-logging

volumes:
  expertiza-mysql:
  expertiza-redis:

networks:
  public:
  private:
