default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "expertiza") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "reimplementation_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME", "reimplementation_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_PRODUCTION_NAME", "reimplementation_production") %>
