providers:
  google-ncsu:
    display_name: Google NCSU
    issuer: https://accounts.google.com
    client_id: <%= ENV['GOOG_CLIENT_ID'] %>
    client_secret: <%= ENV['GOOG_CLIENT_SECRET'] %>
    redirect_uri: <%= ENV['GOOG_REDIRECT_URI'] %>

# Add more providers here:
  # okta:
  #   display_name: Okta
  #   icon: okta
  #   issuer: https://<your-okta-domain>.okta.com
  #   client_id: <%= ENV['OKTA_OIDC_CLIENT_ID'] %>
  #   client_secret: <%= ENV['OKTA_OIDC_CLIENT_SECRET'] %>
  #   redirect_uri: <%= ENV['OKTA_OIDC_REDIRECT_URI'] %>
  #   scopes: openid email profile